name: 🎉 Build Binary Test
on:
  workflow_dispatch:
jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Set up Go 1.17
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go

      - name: Set up libpcap-dev
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install libpcap-dev gcc -y

#      - name: Set up Darwin libpcap
#        if: matrix.os == 'macos-latest'
#        run: brew install libpcap

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Build On Linux
        run: go build -o ./ksubdomain_${{ runner.os }} ./cmd/
        if: matrix.os == 'ubuntu-latest'
        env:
          GOENABLE: 1
          CGO_LDFLAGS: "-Wl,-static -L/usr/lib/x86_64-linux-gnu/libpcap.a -lpcap -Wl,-Bdynamic"
      - name: Build On Darwin
        run: go build -o ./ksubdomain_${{ runner.os }} ./cmd/
        if: matrix.os == 'macos-latest'
      - name: Build On Windows
        run: go build -o ./ksubdomain_windows.exe ./cmd/
        if: matrix.os == 'ubuntu-latest'
        env:
          GOOS: windows
          GOENABLE: 1

      - name: Upload a build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ksubdomain_${{ runner.os }}_amd64
          path: ksubdomain*
          if-no-files-found: error